### ISSUE TITLE
Do you know if this would work with redux-persist?

### ISSUE THREAD

**Issue by dchersey** [bhanuc/react-native-fs-store#3]
I'm looking to be able to store larger redux-stores in Async Storage; having outofmemory errors persisting the redux store.  

Any idea if this has been tested by others with redux-persist?

**Comment by bhanuc** [comment]
Not sure if this has been tested with redux-persist. But after going through the docs, dropping this should quite straightforward. Kindly re-open the issue if you find any problem with the module
